version: "3.8"  # Specify a Compose file version

services:
  yocto-build:
    image: dunfellcontainer
    stdin_open: true
    tty: true
    volumes:
      - ./build:/yoctobuild
      - ./meta-example:/home/$USER/Build/yocto/dunfell-container/meta-example
      - ./meta-tegra:/home/$USER/Build/yocto/dunfell-container/meta-tegra
      - ./poky:/home/$USER/Build/yocto/dunfell-container/poky
#      - ./yocto-project-dir:/path/to/yocto/project  # If needed for source code

    build:
      context: ./
      args:
        USER_NAME: $USER
        host_uid: 1000
        host_gid: 1000
